/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing_05;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author RYZEN
 */
public class VentanaSwing10 extends javax.swing.JFrame {

    List<Obrero> obreros_al = new ArrayList<Obrero>();
    DefaultListModel dlm = new DefaultListModel();

    public VentanaSwing10() {
        initComponents();
        lstObreros.setModel(dlm);
        cargarArrayList();
        
        for(int i=0; i<obreros_al.size(); i++) {
            Obrero obrero = obreros_al.get(i);
            dlm.addElement(obrero.getIdObrero() + "             " + obrero.getNombre());
        }
        personalizarVentana();
    }
    
    public void personalizarVentana() {
        ImageIcon icono = new ImageIcon("imagen/cross1.png");
        Image image = icono.getImage();

        this.setIconImage(image);//Cambiar el icono de la ventana
        this.setTitle("VENTANA SWING");//Poner título a la ventana
        //this.setSize(400, 400); //Poner un ancho y altura a la ventana
        this.getContentPane().setBackground(Color.LIGHT_GRAY);//Cambiar el color de fondo de la ventana
        this.setLocationRelativeTo(null); //Centrar la ventana en la pantalla
        this.setResizable(false);//Desactivar el redimencionamiento del JFrame
        this.toFront(); //Poner la ventana al frente de todas
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    public void cargarArrayList() {
        obreros_al.add(new Obrero("C01", "Luis", 50));       //0   
        obreros_al.add(new Obrero("C02", "Miguel", 40));     //1 
        obreros_al.add(new Obrero("C03", "Carlos", 89));     //2 
        obreros_al.add(new Obrero("C04", "María", 60));      //3  
        obreros_al.add(new Obrero("C05", "Arturo", 89));     //4  
        obreros_al.add(new Obrero("C06", "Sandra", 52));     //5   
        obreros_al.add(new Obrero("C07", "Vanessa", 45));    //6 
        obreros_al.add(new Obrero("C08", "María", 87));      //7 
        obreros_al.add(new Obrero("C09", "Antonio", 62));    //8  
        obreros_al.add(new Obrero("C10", "Carla", 80));     //9  
        obreros_al.add(new Obrero("C11", "Ismael", 42));    //10   
        obreros_al.add(new Obrero("C12", "Antonia", 45));   //11 
        obreros_al.add(new Obrero("C13", "María", 77));     //12 
        obreros_al.add(new Obrero("C14", "Miguel", 52));    //13  
        obreros_al.add(new Obrero("C15", "Jose", 70));      //14  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstObreros = new javax.swing.JList<>();
        botMostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaContenido = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("LISTADO DE OBREROS");

        jScrollPane1.setViewportView(lstObreros);

        botMostrar.setText("MOSTRAR");
        botMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botMostrarActionPerformed(evt);
            }
        });

        txaContenido.setColumns(20);
        txaContenido.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txaContenido.setRows(5);
        jScrollPane2.setViewportView(txaContenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botMostrar)
                .addGap(157, 157, 157))
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botMostrar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botMostrarActionPerformed
        txaContenido.setText("");
        int[] x = lstObreros.getSelectedIndices();
        String encabezado;
        encabezado = String.format("%10s       %-10s\n", "IDOBRERO","NOMBRE");
        txaContenido.append(encabezado);
        encabezado = String.format("%10s       %-10s\n", "--------","------");
        txaContenido.append(encabezado);
        for(int i: x) {
            Obrero obrero = obreros_al.get(i);
            String cadena = String.format("%10s       %-10s\n", obrero.getIdObrero(),obrero.getNombre());
            txaContenido.append(cadena);
        }
    }//GEN-LAST:event_botMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSwing10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSwing10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSwing10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSwing10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSwing10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botMostrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstObreros;
    private javax.swing.JTextArea txaContenido;
    // End of variables declaration//GEN-END:variables
}
