package swing_04;

import java.awt.event.ItemEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class VentanaSwing09 extends javax.swing.JFrame {

    String[] continente = {"EUROPA", "AMERICA SUR", "AFRICA", "OCEANIA"};
    String[] europa = {"ALEMANIA", "ESPAÑA", "FRANCIA", "PORTUGAL", "SUECIA"};
    String[] americasur = {"ARGENTINA", "COLOMBIA", "VENEZUELA", "PERU", "CHILE", "PARAGUAY"};
    String[] africa = {"MARRUECO", "ARGELIA", "LIBIA", "CAMERUN", "EGIPTO", "TOGO"};
    String[] oceania = {"AUSTRALIA", "NUEVA ZELANDA"};

    DefaultListModel dlm = new DefaultListModel();

    public VentanaSwing09() {
        initComponents();
        lstPais.setModel(dlm);
        cargarComboBox();
    }

    public void cargarComboBox() {
        for (int i = 0; i < continente.length; i++) {
            cboContinente.addItem(continente[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboContinente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPais = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboContinente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboContinenteItemStateChanged(evt);
            }
        });

        jScrollPane1.setViewportView(lstPais);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(cboContinente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboContinente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboContinenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboContinenteItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String continente = (String) cboContinente.getSelectedItem();
            if (continente.equals(("EUROPA"))) {
                llenarLista("EUROPA");
            } else if (continente.equals(("AMERICA SUR"))) {
                llenarLista("AMERICA SUR");
            } else if (continente.equals(("AFRICA"))) {
                llenarLista("AFRICA");
            } else if (continente.equals(("OCEANIA"))) {
                llenarLista("OCEANIA");
            }
        }
    }//GEN-LAST:event_cboContinenteItemStateChanged

    public void llenarLista(String continente) {

        switch (continente) {
            case "EUROPA":
                dlm.clear();
                for (int i = 0; i < europa.length; i++) {
                    dlm.addElement(europa[i]);
                }
                break;
            case "AMERICA SUR":
                dlm.clear();
                for (int i = 0; i < americasur.length; i++) {
                    dlm.addElement(americasur[i]);
                }
                break;
            case "AFRICA":
                dlm.clear();
                for (int i = 0; i < africa.length; i++) {
                    dlm.addElement(africa[i]);
                }
                break;
            case "OCEANIA":
                dlm.clear();
                for (int i = 0; i < oceania.length; i++) {
                    dlm.addElement(oceania[i]);
                }
                break;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSwing09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSwing09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSwing09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSwing09.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSwing09().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboContinente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstPais;
    // End of variables declaration//GEN-END:variables
}
